# Generated by Django 5.2.5 on 2026-04-20 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Form16PartA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "financial_year",
                    models.CharField(
                        choices=[
                            ("2023-24", "FY 2023-24"),
                            ("2024-25", "FY 2024-25"),
                            ("2025-26", "FY 2025-26"),
                            ("2026-27", "FY 2026-27"),
                            ("2027-28", "FY 2027-28"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "employer_tan",
                    models.CharField(help_text="Employer TAN number", max_length=10),
                ),
                (
                    "employer_pan",
                    models.CharField(help_text="Employer PAN number", max_length=10),
                ),
                ("employer_name", models.CharField(max_length=200)),
                ("employer_address", models.TextField(blank=True, default="")),
                ("employee_pan", models.CharField(max_length=10)),
                ("employee_name", models.CharField(max_length=200)),
                (
                    "q1_tds_deducted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "q1_tds_deposited",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "q2_tds_deducted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "q2_tds_deposited",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "q3_tds_deducted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "q3_tds_deposited",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "q4_tds_deducted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "q4_tds_deposited",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_tds_deducted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_tds_deposited",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_generated", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "form16_part_a",
                "ordering": ["-financial_year", "employee__name"],
            },
        ),
        migrations.CreateModel(
            name="Form16PartB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "financial_year",
                    models.CharField(
                        choices=[
                            ("2023-24", "FY 2023-24"),
                            ("2024-25", "FY 2024-25"),
                            ("2025-26", "FY 2025-26"),
                            ("2026-27", "FY 2026-27"),
                            ("2027-28", "FY 2027-28"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "gross_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "hra_received",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "hra_exemption",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_exemptions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "standard_deduction",
                    models.DecimalField(decimal_places=2, default=50000, max_digits=10),
                ),
                (
                    "professional_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "income_from_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "deduction_80c",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "deduction_80ccd1b",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "deduction_80d",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "deduction_80e",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "deduction_80g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "deduction_24b",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_chapter_via",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "taxable_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_on_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "surcharge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cess",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_tax_payable",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "rebate_87a",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "relief_89",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "net_tax_payable",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tds_deducted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "regime",
                    models.CharField(
                        choices=[("OLD", "Old"), ("NEW", "New")],
                        default="NEW",
                        max_length=5,
                    ),
                ),
                ("is_generated", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "form16_part_b",
                "ordering": ["-financial_year", "employee__name"],
            },
        ),
        migrations.CreateModel(
            name="PayrollConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proration_basis",
                    models.CharField(
                        choices=[
                            (
                                "CALENDAR_DAYS",
                                "Calendar Days (payable / days_in_month)",
                            ),
                            ("WORKING_DAYS", "Working Days (payable / working_days)"),
                        ],
                        default="CALENDAR_DAYS",
                        help_text="Basis for salary proration when employee has LOP days.",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_from",
                    models.DateField(
                        help_text="Date from which this configuration is effective."
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Payroll Config",
                "verbose_name_plural": "Payroll Configs",
                "db_table": "payroll_configs",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="ProfessionalTaxSlab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_monthly_wage",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.00",
                        help_text="Minimum monthly gross wage for this slab (inclusive)",
                        max_digits=10,
                    ),
                ),
                (
                    "max_monthly_wage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum monthly gross wage for this slab (inclusive). Null = no upper limit (top slab).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "pt_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.00",
                        help_text="Monthly PT amount in rupees for employees in this wage range",
                        max_digits=8,
                    ),
                ),
                (
                    "applicable_months",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of month numbers (1=Jan … 12=Dec) when this slab applies. Empty list = applies to all months. Use this for states like Karnataka where March has a different PT amount.",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                        ],
                        default="ALL",
                        help_text="Gender applicability. Most states use ALL.",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Professional Tax Slab",
                "verbose_name_plural": "Professional Tax Slabs",
                "db_table": "professional_tax_slabs",
                "ordering": ["statutory_config", "display_order", "min_monthly_wage"],
            },
        ),
        migrations.CreateModel(
            name="SalaryComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code used in formulas and reports (e.g. BASIC, HRA, PF_EMP)",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("EARNING", "Earning"),
                            ("DEDUCTION", "Deduction"),
                            ("EMPLOYER_CONTRIBUTION", "Employer Contribution"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("FIXED_AMOUNT", "Fixed Amount"),
                            ("PERCENTAGE_OF_BASIC", "Percentage of Basic"),
                            ("PERCENTAGE_OF_GROSS", "Percentage of Gross"),
                            ("PERCENTAGE_OF_CTC", "Percentage of CTC"),
                            ("STATUTORY", "Statutory (PF / ESI / PT)"),
                            ("FORMULA", "Formula"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "default_value",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Amount (for FIXED_AMOUNT) or percentage (for PERCENTAGE_OF_* types)",
                        max_digits=10,
                    ),
                ),
                (
                    "formula",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Python-safe expression evaluated at payroll time. Available vars: BASIC, GROSS, CTC_MONTHLY, and other component codes.",
                    ),
                ),
                (
                    "is_taxable",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this component is taxable under income tax",
                    ),
                ),
                (
                    "affects_gross",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this component is included in gross earnings",
                    ),
                ),
                (
                    "affects_net",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this component affects net pay (earnings add, deductions subtract)",
                    ),
                ),
                (
                    "affects_ctc",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this component is counted in CTC",
                    ),
                ),
                (
                    "is_pf_applicable",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this component is included in PF wage calculation",
                    ),
                ),
                (
                    "is_esi_applicable",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this component is included in ESI wage calculation",
                    ),
                ),
                (
                    "is_statutory",
                    models.BooleanField(
                        default=False,
                        help_text="True for PF, ESI, PT — statutory components cannot be freely removed from templates",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=True, help_text="Monthly recurring vs one-time payment"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which this component appears on the payslip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary Component",
                "verbose_name_plural": "Salary Components",
                "db_table": "salary_components",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SalaryTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short unique code (e.g. SWE_L1, MGR_A, INTERN)",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Salary Template",
                "verbose_name_plural": "Salary Templates",
                "db_table": "salary_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SalaryTemplateComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calculation_type_override",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FIXED_AMOUNT", "Fixed Amount"),
                            ("PERCENTAGE_OF_BASIC", "Percentage of Basic"),
                            ("PERCENTAGE_OF_GROSS", "Percentage of Gross"),
                            ("PERCENTAGE_OF_CTC", "Percentage of CTC"),
                            ("STATUTORY", "Statutory (PF / ESI / PT)"),
                            ("FORMULA", "Formula"),
                        ],
                        help_text="Override the component default calculation type for this template",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Amount or percentage for this component in this template",
                        max_digits=10,
                    ),
                ),
                (
                    "formula_override",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Override formula for this template (only used if calculation_type is FORMULA)",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Salary Template Component",
                "verbose_name_plural": "Salary Template Components",
                "db_table": "salary_template_components",
                "ordering": ["display_order", "component__display_order"],
            },
        ),
        migrations.CreateModel(
            name="StatutoryConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "financial_year",
                    models.CharField(
                        choices=[
                            ("2023-24", "FY 2023-24"),
                            ("2024-25", "FY 2024-25"),
                            ("2025-26", "FY 2025-26"),
                            ("2026-27", "FY 2026-27"),
                            ("2027-28", "FY 2027-28"),
                        ],
                        help_text="Financial year this config applies to (e.g. 2025-26)",
                        max_length=10,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AP", "Andhra Pradesh"),
                            ("AR", "Arunachal Pradesh"),
                            ("AS", "Assam"),
                            ("BR", "Bihar"),
                            ("CG", "Chhattisgarh"),
                            ("GA", "Goa"),
                            ("GJ", "Gujarat"),
                            ("HR", "Haryana"),
                            ("HP", "Himachal Pradesh"),
                            ("JH", "Jharkhand"),
                            ("KA", "Karnataka"),
                            ("KL", "Kerala"),
                            ("MP", "Madhya Pradesh"),
                            ("MH", "Maharashtra"),
                            ("MN", "Manipur"),
                            ("ML", "Meghalaya"),
                            ("MZ", "Mizoram"),
                            ("NL", "Nagaland"),
                            ("OD", "Odisha"),
                            ("PB", "Punjab"),
                            ("RJ", "Rajasthan"),
                            ("SK", "Sikkim"),
                            ("TN", "Tamil Nadu"),
                            ("TG", "Telangana"),
                            ("TR", "Tripura"),
                            ("UP", "Uttar Pradesh"),
                            ("UK", "Uttarakhand"),
                            ("WB", "West Bengal"),
                            ("DL", "Delhi"),
                            ("OTHER", "Other / Union Territory"),
                        ],
                        help_text="State this config applies to. Use the state where the company/branch is registered.",
                        max_length=10,
                    ),
                ),
                (
                    "pf_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether PF deductions are enabled for this config",
                    ),
                ),
                (
                    "pf_employee_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default="0.1200",
                        help_text="Employee PF contribution rate (e.g. 0.1200 = 12%)",
                        max_digits=5,
                    ),
                ),
                (
                    "pf_employer_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default="0.1200",
                        help_text="Employer PF contribution rate (e.g. 0.1200 = 12%)",
                        max_digits=5,
                    ),
                ),
                (
                    "pf_wage_ceiling",
                    models.DecimalField(
                        decimal_places=2,
                        default="15000.00",
                        help_text="Monthly PF wage ceiling in rupees. PF is calculated on min(actual_pf_wage, ceiling).",
                        max_digits=10,
                    ),
                ),
                (
                    "pf_rounding",
                    models.CharField(
                        choices=[
                            ("ROUND", "Round to nearest rupee"),
                            ("FLOOR", "Floor (round down)"),
                            ("CEIL", "Ceiling (round up)"),
                        ],
                        default="ROUND",
                        help_text="How to round PF contribution amounts",
                        max_length=10,
                    ),
                ),
                (
                    "pf_include_employer_in_ctc",
                    models.BooleanField(
                        default=True,
                        help_text="Whether employer PF contribution is included in CTC calculation",
                    ),
                ),
                (
                    "esi_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether ESI deductions are enabled for this config",
                    ),
                ),
                (
                    "esi_employee_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default="0.0075",
                        help_text="Employee ESI contribution rate (e.g. 0.0075 = 0.75%)",
                        max_digits=5,
                    ),
                ),
                (
                    "esi_employer_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default="0.0325",
                        help_text="Employer ESI contribution rate (e.g. 0.0325 = 3.25%)",
                        max_digits=5,
                    ),
                ),
                (
                    "esi_wage_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default="21000.00",
                        help_text="Monthly gross wage threshold. Employees earning above this are NOT ESI-covered.",
                        max_digits=10,
                    ),
                ),
                (
                    "pt_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether Professional Tax is enabled. PT slabs are defined in ProfessionalTaxSlab.",
                    ),
                ),
                (
                    "lwf_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether Labour Welfare Fund deductions are enabled",
                    ),
                ),
                (
                    "lwf_employee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.00",
                        help_text="Employee LWF contribution amount per applicable period",
                        max_digits=8,
                    ),
                ),
                (
                    "lwf_employer_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.00",
                        help_text="Employer LWF contribution amount per applicable period",
                        max_digits=8,
                    ),
                ),
                (
                    "lwf_applicable_months",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of month numbers (1-12) when LWF is deducted. Empty = every month.",
                    ),
                ),
                (
                    "tds_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether TDS deductions are enabled. Full TDS engine is a future phase.",
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        help_text="Date from which this config is effective"
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Date until which this config is effective. Null = currently active.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Statutory Config",
                "verbose_name_plural": "Statutory Configs",
                "db_table": "statutory_configs",
                "ordering": ["-financial_year", "state"],
            },
        ),
        migrations.CreateModel(
            name="TaxAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("DECLARATION_SUBMITTED", "Declaration Submitted"),
                            ("DECLARATION_APPROVED", "Declaration Approved"),
                            ("DECLARATION_REJECTED", "Declaration Rejected"),
                            ("REGIME_CHANGED", "Tax Regime Changed"),
                            ("TDS_OVERRIDE_SET", "TDS Override Set"),
                            ("TDS_OVERRIDE_CLEARED", "TDS Override Cleared"),
                            ("FORM16_GENERATED", "Form 16 Generated"),
                            ("YTD_UPDATED", "YTD Record Updated"),
                            ("EXEMPT_STATUS_CHANGED", "Exempt Status Changed"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "financial_year",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "field_changed",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("old_value", models.TextField(blank=True, default="")),
                ("new_value", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tax_audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TaxRegimeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "financial_year",
                    models.CharField(
                        choices=[
                            ("2023-24", "FY 2023-24"),
                            ("2024-25", "FY 2024-25"),
                            ("2025-26", "FY 2025-26"),
                            ("2026-27", "FY 2026-27"),
                            ("2027-28", "FY 2027-28"),
                        ],
                        help_text="Financial year this config applies to (e.g. 2025-26)",
                        max_length=10,
                    ),
                ),
                (
                    "regime",
                    models.CharField(
                        choices=[
                            ("OLD", "Old Tax Regime"),
                            ("NEW", "New Tax Regime (Default from FY 2023-24)"),
                        ],
                        help_text="OLD = pre-2023 regime with deductions; NEW = simplified slab regime",
                        max_length=5,
                    ),
                ),
                (
                    "standard_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default="50000.00",
                        help_text="Standard deduction from salary income (₹50,000 old / ₹75,000 new as of FY 2025-26)",
                        max_digits=10,
                    ),
                ),
                (
                    "rebate_87a_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default="500000.00",
                        help_text="Taxable income ceiling below which full 87A rebate applies",
                        max_digits=12,
                    ),
                ),
                (
                    "rebate_87a_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default="12500.00",
                        help_text="Maximum rebate amount under Section 87A",
                        max_digits=10,
                    ),
                ),
                (
                    "surcharge_slabs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Surcharge slabs: [{from, to, rate}]. to=null means no upper limit.",
                    ),
                ),
                (
                    "cess_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default="0.0400",
                        help_text="Health and Education cess rate (4% = 0.0400)",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tax Regime Config",
                "verbose_name_plural": "Tax Regime Configs",
                "db_table": "tax_regime_configs",
                "ordering": ["-financial_year", "regime"],
            },
        ),
        migrations.CreateModel(
            name="TaxSlab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "income_from",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.00",
                        help_text="Lower bound of this slab (inclusive), in rupees",
                        max_digits=14,
                    ),
                ),
                (
                    "income_to",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Upper bound of this slab (inclusive), in rupees. Null = no upper limit.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Tax rate for this slab (e.g. 0.0500 = 5%)",
                        max_digits=5,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Tax Slab",
                "verbose_name_plural": "Tax Slabs",
                "db_table": "tax_slabs",
                "ordering": ["regime_config", "display_order", "income_from"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeSalaryAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annual_ctc",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual CTC in rupees (e.g. 600000 for 6 LPA)",
                        max_digits=14,
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        help_text="Date from which this salary structure is effective"
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Date until which this assignment is effective. Null = currently active.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only one active assignment per employee at a time",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text='Reason for revision or any notes (e.g. "Annual increment FY 2025-26")',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_salary_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_assignments",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Salary Assignment",
                "verbose_name_plural": "Employee Salary Assignments",
                "db_table": "employee_salary_assignments",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeYTDRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "financial_year",
                    models.CharField(
                        choices=[
                            ("2023-24", "FY 2023-24"),
                            ("2024-25", "FY 2024-25"),
                            ("2025-26", "FY 2025-26"),
                            ("2026-27", "FY 2026-27"),
                            ("2027-28", "FY 2027-28"),
                        ],
                        help_text="Financial year (e.g. 2025-26)",
                        max_length=10,
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        help_text="Calendar month number (1=Jan … 12=Dec)"
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="Calendar year (e.g. 2026)"
                    ),
                ),
                (
                    "ytd_gross_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.00",
                        help_text="Sum of gross earnings from April to this month",
                        max_digits=14,
                    ),
                ),
                (
                    "ytd_taxable_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.00",
                        help_text="Sum of taxable component earnings (is_taxable=True) from April to this month",
                        max_digits=14,
                    ),
                ),
                (
                    "ytd_deductions_80c",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.00",
                        help_text="Sum of 80C-eligible deductions (PF employee, ELSS, etc.) from April to this month",
                        max_digits=14,
                    ),
                ),
                (
                    "ytd_other_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.00",
                        help_text="Sum of other declared deductions (HRA exemption, NPS, etc.) from April to this month",
                        max_digits=14,
                    ),
                ),
                (
                    "ytd_tds_deducted",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.00",
                        help_text="Sum of TDS actually deducted from April to this month",
                        max_digits=14,
                    ),
                ),
                (
                    "projected_annual_taxable",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.00",
                        help_text="Projected full-year taxable income based on actuals + remaining months",
                        max_digits=14,
                    ),
                ),
                (
                    "projected_annual_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.00",
                        help_text="Projected full-year income tax liability (before cess)",
                        max_digits=14,
                    ),
                ),
                (
                    "projected_annual_tax_with_cess",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.00",
                        help_text="Projected full-year tax including surcharge and cess",
                        max_digits=14,
                    ),
                ),
                (
                    "remaining_months",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Number of FY months remaining including this month",
                    ),
                ),
                (
                    "monthly_tds",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.00",
                        help_text="TDS to deduct this month = (projected_tax - ytd_tds) / remaining_months",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ytd_records",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee YTD Record",
                "verbose_name_plural": "Employee YTD Records",
                "db_table": "employee_ytd_records",
                "ordering": ["-year", "-month", "employee__name"],
            },
        ),
    ]
