# Generated by Django 5.2.5 on 2026-04-20 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0002_initial"),
        ("payroll_config", "0001_initial"),
        ("payslip_generation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeytdrecord",
            name="payroll_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The payroll run that wrote this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ytd_records",
                to="payslip_generation.payrollrun",
            ),
        ),
        migrations.AddField(
            model_name="form16parta",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form16_part_a",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="form16parta",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_form16_part_a",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="form16partb",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form16_part_b",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="form16partb",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_form16_part_b",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="form16partb",
            name="part_a",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="part_b",
                to="payroll_config.form16parta",
            ),
        ),
        migrations.AddField(
            model_name="payrollconfig",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_payroll_configs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salarytemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_salary_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeesalaryassignment",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_assignments",
                to="payroll_config.salarytemplate",
            ),
        ),
        migrations.AddField(
            model_name="salarytemplatecomponent",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="template_usages",
                to="payroll_config.salarycomponent",
            ),
        ),
        migrations.AddField(
            model_name="salarytemplatecomponent",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="payroll_config.salarytemplate",
            ),
        ),
        migrations.AddField(
            model_name="statutoryconfig",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_statutory_configs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="professionaltaxslab",
            name="statutory_config",
            field=models.ForeignKey(
                help_text="The statutory config this slab belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pt_slabs",
                to="payroll_config.statutoryconfig",
            ),
        ),
        migrations.AddField(
            model_name="taxauditlog",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_audit_logs",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="taxauditlog",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tax_audit_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taxregimeconfig",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tax_regime_configs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taxslab",
            name="regime_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slabs",
                to="payroll_config.taxregimeconfig",
            ),
        ),
        migrations.AddIndex(
            model_name="employeeytdrecord",
            index=models.Index(
                fields=["employee", "financial_year"], name="ytd_emp_fy_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeeytdrecord",
            index=models.Index(
                fields=["financial_year", "month", "year"], name="ytd_fy_period_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employeeytdrecord",
            unique_together={("employee", "financial_year", "month", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="form16parta",
            unique_together={("employee", "financial_year")},
        ),
        migrations.AlterUniqueTogether(
            name="form16partb",
            unique_together={("employee", "financial_year")},
        ),
        migrations.AddIndex(
            model_name="employeesalaryassignment",
            index=models.Index(
                fields=["employee", "is_active"], name="esa_employee_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeesalaryassignment",
            index=models.Index(
                fields=["employee", "effective_from"], name="esa_employee_eff_from_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salarytemplatecomponent",
            unique_together={("template", "component")},
        ),
        migrations.AddIndex(
            model_name="statutoryconfig",
            index=models.Index(
                fields=["state", "is_active"], name="sc_state_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statutoryconfig",
            index=models.Index(
                fields=["financial_year", "state"], name="sc_fy_state_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="statutoryconfig",
            unique_together={("financial_year", "state", "is_active")},
        ),
        migrations.AddIndex(
            model_name="taxauditlog",
            index=models.Index(
                fields=["employee", "financial_year"], name="tal_emp_fy_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxauditlog",
            index=models.Index(
                fields=["action", "timestamp"], name="tal_action_ts_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taxregimeconfig",
            unique_together={("financial_year", "regime")},
        ),
    ]
