# Generated by Django 5.2.5 on 2026-04-20 08:07

import attendance.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegacyHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("holiday_date", models.DateField(unique=True)),
                ("is_optional", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "attendance_holidays",
                "ordering": ["holiday_date"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AttendanceAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE", "Employee"),
                            ("ADMIN", "Admin"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("PUNCH_IN", "Punch In"),
                            ("PUNCH_OUT", "Punch Out"),
                            ("MANUAL_UPDATE", "Manual Update"),
                            ("AUTO_ABSENT", "Auto Absent"),
                            ("CREATE", "Create"),
                        ],
                        max_length=30,
                    ),
                ),
                ("before_data", models.JSONField(blank=True, default=dict)),
                ("after_data", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "attendance_audit_logs",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AttendancePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("enforce_gps", models.BooleanField(default=True)),
                ("allow_remote_punch", models.BooleanField(default=False)),
                (
                    "allowed_work_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of allowed work types e.g. ["WFO", "WFH", "ONSITE"]. Empty = all allowed.',
                    ),
                ),
                ("auto_mark_absent", models.BooleanField(default=True)),
                (
                    "min_half_day_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("4.00"), max_digits=4
                    ),
                ),
                (
                    "full_day_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("8.00"), max_digits=4
                    ),
                ),
                (
                    "week_off_days",
                    models.JSONField(
                        blank=True, default=attendance.models.default_week_off_days
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "attendance_policies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("punch_in_time", models.DateTimeField(blank=True, null=True)),
                ("punch_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "punch_in_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "punch_in_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "punch_out_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "punch_out_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("location_verified", models.BooleanField(default=False)),
                ("punch_out_location_verified", models.BooleanField(default=False)),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("WFO", "Work From Office"),
                            ("WFH", "Work From Home"),
                            ("ONSITE", "On-site / Client Location"),
                        ],
                        default="WFO",
                        help_text="Work mode selected at punch-in: WFO, WFH, or ONSITE",
                        max_length=10,
                    ),
                ),
                (
                    "working_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("LATE", "Late"),
                            ("HALF_DAY", "Half Day"),
                            ("ABSENT", "Absent"),
                            ("LEAVE", "Leave"),
                            ("HOLIDAY", "Holiday"),
                            ("WEEK_OFF", "Week Off"),
                        ],
                        default="ABSENT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("marked_by_system", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "attendance_records",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeShiftAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "attendance_employee_shift_assignments",
                "ordering": ["-effective_from", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=120)),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("NATIONAL", "National Holiday"),
                            ("OPTIONAL", "Optional Holiday"),
                            ("RESTRICTED", "Restricted Holiday"),
                        ],
                        default="NATIONAL",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "holiday_calendar_entries",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="HolidayCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="Calendar year (e.g. 2026). All holidays must fall within this year."
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AP", "Andhra Pradesh"),
                            ("AR", "Arunachal Pradesh"),
                            ("AS", "Assam"),
                            ("BR", "Bihar"),
                            ("CG", "Chhattisgarh"),
                            ("GA", "Goa"),
                            ("GJ", "Gujarat"),
                            ("HR", "Haryana"),
                            ("HP", "Himachal Pradesh"),
                            ("JH", "Jharkhand"),
                            ("KA", "Karnataka"),
                            ("KL", "Kerala"),
                            ("MP", "Madhya Pradesh"),
                            ("MH", "Maharashtra"),
                            ("MN", "Manipur"),
                            ("ML", "Meghalaya"),
                            ("MZ", "Mizoram"),
                            ("NL", "Nagaland"),
                            ("OD", "Odisha"),
                            ("PB", "Punjab"),
                            ("RJ", "Rajasthan"),
                            ("SK", "Sikkim"),
                            ("TN", "Tamil Nadu"),
                            ("TG", "Telangana"),
                            ("TR", "Tripura"),
                            ("UP", "Uttar Pradesh"),
                            ("UK", "Uttarakhand"),
                            ("WB", "West Bengal"),
                            ("DL", "Delhi"),
                            ("OTHER", "Other / Union Territory"),
                        ],
                        help_text="Indian state code. Null = company-wide calendar (applies to all states).",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "holiday_calendars",
                "ordering": ["-year", "state"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyAttendanceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                ("present_days", models.PositiveSmallIntegerField(default=0)),
                ("late_days", models.PositiveSmallIntegerField(default=0)),
                ("leave_days", models.PositiveSmallIntegerField(default=0)),
                ("absent_days", models.PositiveSmallIntegerField(default=0)),
                ("half_days", models.PositiveSmallIntegerField(default=0)),
                (
                    "total_working_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=7
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=7
                    ),
                ),
                (
                    "payable_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "attendance_monthly_summaries",
                "ordering": ["-year", "-month", "employee__name"],
            },
        ),
        migrations.CreateModel(
            name="OfficeLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("allowed_radius_meters", models.PositiveIntegerField(default=200)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "attendance_office_locations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("late_after", models.TimeField()),
                ("half_day_after", models.TimeField()),
                ("overtime_allowed", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "attendance_shifts",
                "ordering": ["name"],
            },
        ),
    ]
