# Generated by Django 5.2.5 on 2026-03-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
        ("employees", "0017_leavetype_employeedocument_leaverequest_notification"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["employee", "date", "status"],
                name="attendance__employe_4ca90e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["punch_in_time"], name="attendance__punch_i_f1e34a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["punch_out_time"], name="attendance__punch_o_1e8f27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyattendancesummary",
            index=models.Index(
                fields=["employee", "month", "year"],
                name="attendance__employe_e623de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyattendancesummary",
            index=models.Index(
                fields=["month", "year"], name="attendance__month_2a3496_idx"
            ),
        ),
    ]
