# Generated by Django 5.2.5 on 2026-04-20 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("attendance", "0002_initial"),
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendanceauditlog",
            name="actor_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_actions",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records_v2",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="attendanceauditlog",
            name="attendance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="attendance.attendancerecord",
            ),
        ),
        migrations.AddField(
            model_name="employeeshiftassignment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shift_assignments_done",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeeshiftassignment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_assignments",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeeshiftassignment",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_assignments",
                to="attendance.attendancepolicy",
            ),
        ),
        migrations.AddField(
            model_name="holidaycalendar",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_holiday_calendars",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="holiday",
            name="calendar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holidays",
                to="attendance.holidaycalendar",
            ),
        ),
        migrations.AddField(
            model_name="monthlyattendancesummary",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_attendance_summaries",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeeshiftassignment",
            name="office_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_assignments",
                to="attendance.officelocation",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="office_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="attendance.officelocation",
            ),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="default_office_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_policy_for",
                to="attendance.officelocation",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_shifts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeeshiftassignment",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_assignments",
                to="attendance.shift",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="attendance.shift",
            ),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="default_shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_policy_for",
                to="attendance.shift",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="holidaycalendar",
            unique_together={("year", "state", "is_active")},
        ),
        migrations.AlterUniqueTogether(
            name="holiday",
            unique_together={("calendar", "date")},
        ),
        migrations.AddIndex(
            model_name="monthlyattendancesummary",
            index=models.Index(
                fields=["employee", "month", "year"],
                name="attendance__employe_e623de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyattendancesummary",
            index=models.Index(
                fields=["month", "year"], name="attendance__month_2a3496_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="monthlyattendancesummary",
            unique_together={("employee", "month", "year")},
        ),
        migrations.AddIndex(
            model_name="employeeshiftassignment",
            index=models.Index(
                fields=["employee", "effective_from", "effective_to"],
                name="attendance__employe_fbde4e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employeeshiftassignment",
            index=models.Index(
                fields=["is_active"], name="attendance__is_acti_567ae7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["date", "status"], name="attendance__date_0c5e7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["employee", "date"], name="attendance__employe_6b3da7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["employee", "date", "status"],
                name="attendance__employe_4ca90e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["punch_in_time"], name="attendance__punch_i_f1e34a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["punch_out_time"], name="attendance__punch_o_1e8f27_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("employee", "date")},
        ),
    ]
