# Generated by Django 5.2.5 on 2026-04-20 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("code", models.CharField(blank=True, max_length=20, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "bank_master",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeESIDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_covered", models.BooleanField(default=False)),
                ("esi_number", models.CharField(blank=True, max_length=30, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "employee_esi_details",
            },
        ),
        migrations.CreateModel(
            name="EmployeeFamilyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("FATHER", "Father"),
                            ("MOTHER", "Mother"),
                            ("SPOUSE", "Spouse"),
                            ("SON", "Son"),
                            ("DAUGHTER", "Daughter"),
                            ("BROTHER", "Brother"),
                            ("SISTER", "Sister"),
                            ("GUARDIAN", "Guardian"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("nationality", models.CharField(blank=True, max_length=60, null=True)),
                ("profession", models.CharField(blank=True, max_length=100, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("address_same_as_employee", models.BooleanField(default=False)),
                (
                    "copy_address_from",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRESENT", "Present Address"),
                            ("PERMANENT", "Permanent Address"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "employee_family_members",
                "ordering": ["relation", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeLWFDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_covered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "employee_lwf_details",
            },
        ),
        migrations.CreateModel(
            name="EmployeePFDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_covered", models.BooleanField(default=False)),
                ("uan", models.CharField(blank=True, max_length=20, null=True)),
                ("pf_number", models.CharField(blank=True, max_length=30, null=True)),
                ("pf_join_date", models.DateField(blank=True, null=True)),
                (
                    "family_pf_no",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("is_existing_eps_member", models.BooleanField(default=False)),
                ("allow_epf_excess", models.BooleanField(default=False)),
                ("allow_eps_excess", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "employee_pf_details",
            },
        ),
        migrations.CreateModel(
            name="BankBranchMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_name", models.CharField(max_length=120)),
                ("ifsc_code", models.CharField(max_length=15)),
                ("city", models.CharField(blank=True, max_length=80, null=True)),
                ("state", models.CharField(blank=True, max_length=80, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="employee_finance.bankmaster",
                    ),
                ),
            ],
            options={
                "db_table": "bank_branch_master",
                "ordering": ["branch_name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeBankDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_account_no",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("ifsc_code", models.CharField(blank=True, max_length=15, null=True)),
                ("iban", models.CharField(blank=True, max_length=34, null=True)),
                (
                    "account_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SAVING", "Saving"),
                            ("CURRENT", "Current"),
                            ("FIXED", "Fixed"),
                            ("SALARIED", "Salaried Account"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEFT", "NEFT / Bank Transfer"),
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                            ("DD", "Demand Draft"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "dd_payable_at",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "name_as_per_bank",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee_finance.bankmaster",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee_finance.bankbranchmaster",
                    ),
                ),
            ],
            options={
                "db_table": "employee_bank_details",
            },
        ),
    ]
