# Generated by Django 5.2.5 on 2026-04-20 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employee_finance", "0001_initial"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeebankdetail",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_detail",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeeesidetail",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="esi_detail",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeefamilymember",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="family_members",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeelwfdetail",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lwf_detail",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeepfdetail",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pf_detail",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeepfdetail",
            name="verification_document",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee document used as PF verification proof",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pf_verifications",
                to="employees.employeedocument",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bankbranchmaster",
            unique_together={("bank", "ifsc_code")},
        ),
    ]
