# Generated by Django 4.2.7 on 2025-09-04 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayslipGenerationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("employee_ids", models.JSONField()),
                ("pay_period_month", models.CharField(max_length=20)),
                ("pay_period_year", models.IntegerField()),
                ("salary_type", models.CharField(max_length=20)),
                ("total_employees", models.IntegerField()),
                ("completed_employees", models.IntegerField(default=0)),
                ("failed_employees", models.IntegerField(default=0)),
                ("current_batch", models.IntegerField(default=0)),
                ("total_batches", models.IntegerField(default=0)),
                ("batch_size", models.IntegerField(default=25)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslip_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payslip Generation Task",
                "verbose_name_plural": "Payslip Generation Tasks",
                "db_table": "payslip_generation_tasks",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pay_period_month", models.CharField(max_length=20)),
                ("pay_period_year", models.IntegerField()),
                (
                    "salary_type",
                    models.CharField(
                        choices=[("SALARY", "Salary"), ("STIPEND", "Stipend")],
                        max_length=20,
                    ),
                ),
                ("work_days", models.IntegerField()),
                ("days_in_month", models.IntegerField()),
                (
                    "lop_days",
                    models.IntegerField(default=0, verbose_name="Loss of Pay Days"),
                ),
                ("basic", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "hra",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="House Rent Allowance",
                    ),
                ),
                (
                    "da",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Dearness Allowance",
                    ),
                ),
                ("conveyance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("medical", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "special_allowance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pf_employee",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="PF Employee"
                    ),
                ),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "professional_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pf_employer",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="PF Employer"
                    ),
                ),
                (
                    "other_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "salary_advance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("net_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pdf_path", models.CharField(max_length=255)),
                ("qr_code_data", models.TextField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="employees.employee",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_payslips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payslip",
                "verbose_name_plural": "Payslips",
                "db_table": "payslips",
                "ordering": ["-generated_at"],
                "unique_together": {
                    ("employee", "pay_period_month", "pay_period_year", "salary_type")
                },
            },
        ),
    ]
