# Generated by Django 5.2.5 on 2026-04-20 08:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        ("payroll_config", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20)),
                ("year", models.IntegerField()),
                (
                    "salary_type",
                    models.CharField(
                        choices=[("SALARY", "Salary"), ("STIPEND", "Stipend")],
                        default="SALARY",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CALCULATED", "Calculated"),
                            ("REVIEWED", "Reviewed"),
                            ("APPROVED", "Approved"),
                            ("LOCKED", "Locked"),
                            ("RELEASED", "Released"),
                            ("PAID", "Paid"),
                            ("REOPENED", "Reopened"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("total_employees", models.IntegerField(default=0)),
                (
                    "total_gross",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_net",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("reopen_reason", models.TextField(blank=True, default="")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="released_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Run",
                "verbose_name_plural": "Payroll Runs",
                "db_table": "payroll_runs",
                "ordering": ["-year", "-month"],
                "unique_together": {("month", "year", "salary_type")},
            },
        ),
        migrations.CreateModel(
            name="PayrollRunItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INCLUDED", "Included"),
                            ("ON_HOLD", "On Hold"),
                            ("REPROCESSING", "Reprocessing"),
                            ("ERROR", "Error"),
                        ],
                        default="INCLUDED",
                        max_length=20,
                    ),
                ),
                (
                    "gross_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "employer_contributions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total employer-side contributions (PF employer, ESI employer, LWF employer). Not deducted from employee net pay.",
                        max_digits=12,
                    ),
                ),
                (
                    "net_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("lop_days", models.IntegerField(default=0)),
                ("work_days", models.IntegerField(default=0)),
                (
                    "payable_days",
                    models.IntegerField(
                        default=0,
                        help_text="Actual days payable after LOP (work_days - lop_days)",
                    ),
                ),
                (
                    "days_in_month",
                    models.IntegerField(
                        default=0, help_text="Total calendar days in the payroll month"
                    ),
                ),
                (
                    "proration_factor",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        help_text="payable_days / days_in_month. 1.0 = full month, <1 = prorated.",
                        max_digits=6,
                    ),
                ),
                (
                    "tds_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Income tax (TDS) deducted for this payroll period.",
                        max_digits=10,
                    ),
                ),
                (
                    "calculation_source",
                    models.CharField(
                        choices=[
                            ("SALARY_ASSIGNMENT", "Salary Assignment (3C Engine)"),
                            ("MONTHLY_SALARY_DATA", "Monthly Salary Data (Legacy)"),
                        ],
                        default="MONTHLY_SALARY_DATA",
                        max_length=25,
                    ),
                ),
                (
                    "calculation_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Warnings or informational notes from the calculation engine.",
                    ),
                ),
                ("hold_reason", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                ("calculated_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_run_items",
                        to="employees.employee",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="payslip_generation.payrollrun",
                    ),
                ),
                (
                    "salary_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_run_items",
                        to="payroll_config.employeesalaryassignment",
                    ),
                ),
                (
                    "salary_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_run_items",
                        to="employees.monthlysalarydata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Run Item",
                "verbose_name_plural": "Payroll Run Items",
                "db_table": "payroll_run_items",
                "ordering": ["employee__name"],
            },
        ),
        migrations.CreateModel(
            name="PayrollInputSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_calendar_days", models.PositiveSmallIntegerField(default=0)),
                ("weekly_off_days", models.PositiveSmallIntegerField(default=0)),
                ("holiday_days", models.PositiveSmallIntegerField(default=0)),
                ("working_days", models.PositiveSmallIntegerField(default=0)),
                (
                    "present_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "leave_days_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "leave_days_unpaid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                ("absent_days", models.PositiveSmallIntegerField(default=0)),
                (
                    "lop_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "payable_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "proration_basis",
                    models.CharField(default="CALENDAR_DAYS", max_length=20),
                ),
                (
                    "proration_factor",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1"), max_digits=6
                    ),
                ),
                (
                    "lop_override_used",
                    models.BooleanField(
                        default=False,
                        help_text="True if MonthlySalaryData.lop_override was applied instead of computed LOP.",
                    ),
                ),
                ("snapshot_at", models.DateTimeField(auto_now_add=True)),
                (
                    "warnings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of warning strings from compute_payable_days().",
                    ),
                ),
                (
                    "run_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_snapshot",
                        to="payslip_generation.payrollrunitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Input Snapshot",
                "verbose_name_plural": "Payroll Input Snapshots",
                "db_table": "payroll_input_snapshots",
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pay_period_month", models.CharField(max_length=20)),
                ("pay_period_year", models.IntegerField()),
                (
                    "salary_type",
                    models.CharField(
                        choices=[("SALARY", "Salary"), ("STIPEND", "Stipend")],
                        max_length=20,
                    ),
                ),
                ("work_days", models.IntegerField()),
                ("days_in_month", models.IntegerField()),
                (
                    "lop_days",
                    models.IntegerField(default=0, verbose_name="Loss of Pay Days"),
                ),
                ("basic", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "hra",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="House Rent Allowance",
                    ),
                ),
                (
                    "da",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Dearness Allowance",
                    ),
                ),
                ("conveyance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("medical", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "special_allowance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pf_employee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="PF Employee Contribution",
                    ),
                ),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "professional_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pf_employer",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="PF Employer Contribution",
                    ),
                ),
                (
                    "other_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "salary_advance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("net_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tds_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Income tax (TDS) deducted this month",
                        max_digits=10,
                    ),
                ),
                ("pdf_path", models.CharField(max_length=255)),
                ("qr_code_data", models.TextField()),
                (
                    "is_released",
                    models.BooleanField(
                        default=False,
                        help_text="Whether payslip is released and visible to employee",
                    ),
                ),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="employees.employee",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_payslips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="released_payslips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payslip",
                "verbose_name_plural": "Payslips",
                "db_table": "payslips",
                "ordering": ["-generated_at"],
                "unique_together": {
                    ("employee", "pay_period_month", "pay_period_year", "salary_type")
                },
            },
        ),
        migrations.AddField(
            model_name="payrollrunitem",
            name="payslip",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="run_item",
                to="payslip_generation.payslip",
            ),
        ),
        migrations.CreateModel(
            name="PayrollAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("GENERATE", "Payslip Generated"),
                            ("RELEASE", "Payslip Released"),
                            ("BULK_RELEASE", "Bulk Release"),
                            ("DOWNLOAD", "Payslip Downloaded"),
                            ("EMAIL_SENT", "Email Sent"),
                            ("EMAIL_FAILED", "Email Failed"),
                            ("VALIDATE", "Validation Run"),
                            ("DELETE", "Payslip Deleted"),
                            ("REOPEN", "Payroll Reopened"),
                            ("APPROVE", "Payroll Approved"),
                            ("HOLD", "Employee Held"),
                            ("RELEASE_HOLD", "Employee Hold Released"),
                            ("REPROCESS", "Employee Reprocessed"),
                            ("CALCULATE", "Payroll Calculated"),
                            ("LOCK", "Payroll Locked"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "pay_period_month",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("pay_period_year", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_audit_logs",
                        to="employees.employee",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payslip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="payslip_generation.payslip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Audit Log",
                "verbose_name_plural": "Payroll Audit Logs",
                "db_table": "payroll_audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PayslipGenerationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("employee_ids", models.JSONField()),
                ("pay_period_month", models.CharField(max_length=20)),
                ("pay_period_year", models.IntegerField()),
                ("salary_type", models.CharField(max_length=20)),
                ("total_employees", models.IntegerField()),
                ("completed_employees", models.IntegerField(default=0)),
                ("failed_employees", models.IntegerField(default=0)),
                ("current_batch", models.IntegerField(default=0)),
                ("total_batches", models.IntegerField(default=0)),
                ("batch_size", models.IntegerField(default=25)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslip_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payslip Generation Task",
                "verbose_name_plural": "Payslip Generation Tasks",
                "db_table": "payslip_generation_tasks",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PayrollValidationIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pay_period_month", models.CharField(max_length=20)),
                ("pay_period_year", models.IntegerField()),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("MISSING_SALARY_DATA", "Missing Monthly Salary Data"),
                            ("MISSING_BANK_DETAILS", "Missing Bank Details"),
                            ("MISSING_PF_DETAILS", "Missing PF Details"),
                            ("NEGATIVE_NET_PAY", "Negative Net Pay"),
                            ("DUPLICATE_PAYSLIP", "Duplicate Payslip Exists"),
                            ("MISSING_SALARY_STRUCTURE", "Missing Salary Structure"),
                            ("INACTIVE_EMPLOYEE", "Employee Inactive"),
                            ("MISSING_ATTENDANCE_DATA", "Missing Attendance Data"),
                            ("EXCESSIVE_LOP", "Excessive LOP Days"),
                            ("NEGATIVE_PAYABLE_DAYS", "Negative Payable Days"),
                            ("LOP_OVERRIDE_DIVERGENCE", "LOP Override Divergence"),
                            ("OTHER", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("ERROR", "Error"), ("WARNING", "Warning")],
                        default="ERROR",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_validation_issues",
                        to="employees.employee",
                    ),
                ),
                (
                    "generation_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_issues",
                        to="payslip_generation.payslipgenerationtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Validation Issue",
                "verbose_name_plural": "Payroll Validation Issues",
                "db_table": "payroll_validation_issues",
                "ordering": ["-created_at", "severity"],
            },
        ),
        migrations.CreateModel(
            name="PayrollRunItemLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Component code snapshot", max_length=30
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Component name snapshot", max_length=100
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("EARNING", "Earning"),
                            ("DEDUCTION", "Deduction"),
                            ("EMPLOYER_CONTRIBUTION", "Employer Contribution"),
                        ],
                        help_text="Component type snapshot",
                        max_length=25,
                    ),
                ),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("FIXED_AMOUNT", "Fixed Amount"),
                            ("PERCENTAGE_OF_BASIC", "Percentage of Basic"),
                            ("PERCENTAGE_OF_GROSS", "Percentage of Gross"),
                            ("PERCENTAGE_OF_CTC", "Percentage of CTC"),
                            ("STATUTORY", "Statutory"),
                            ("FORMULA", "Formula"),
                            ("MANUAL", "Manual Override"),
                        ],
                        help_text="Calculation type snapshot",
                        max_length=25,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Rate used: rupee amount for FIXED_AMOUNT, percentage for PERCENTAGE_OF_* types",
                        max_digits=10,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional quantity multiplier (e.g. days, hours)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Final computed amount for this component in this payroll period",
                        max_digits=12,
                    ),
                ),
                ("is_statutory", models.BooleanField(default=False)),
                ("is_taxable", models.BooleanField(default=False)),
                ("affects_gross", models.BooleanField(default=False)),
                ("affects_net_pay", models.BooleanField(default=True)),
                ("affects_ctc", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_run_lines",
                        to="payroll_config.salarycomponent",
                    ),
                ),
                (
                    "run_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="payslip_generation.payrollrunitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Run Item Line",
                "verbose_name_plural": "Payroll Run Item Lines",
                "db_table": "payroll_run_item_lines",
                "ordering": ["display_order", "component_type", "code"],
                "indexes": [
                    models.Index(
                        fields=["run_item", "component_type"], name="pril_item_type_idx"
                    ),
                    models.Index(
                        fields=["run_item", "code"], name="pril_item_code_idx"
                    ),
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="payrollrunitem",
            unique_together={("run", "employee")},
        ),
    ]
