# Generated by Django 5.2.5 on 2026-03-10 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payslip_generation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="is_released",
            field=models.BooleanField(
                default=False,
                help_text="Whether payslip is released and visible to employee",
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="released_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payslip",
            name="released_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="released_payslips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
