# Generated by Django 5.2.5 on 2026-04-20 08:07

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("attendance", "0002_initial"),
        ("departments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeavePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="RDesk Policy", max_length=100)),
                ("earned_leave_per_year", models.IntegerField(default=18)),
                ("casual_leave_per_year", models.IntegerField(default=6)),
                ("sick_leave_per_year", models.IntegerField(default=6)),
                ("el_carry_forward_limit", models.IntegerField(default=30)),
                ("el_encashment_limit", models.IntegerField(default=30)),
                ("accrual_enabled", models.BooleanField(default=True)),
                (
                    "accrual_rate_per_month",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("1.5"), max_digits=4
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Leave Policy",
                "verbose_name_plural": "Leave Policies",
                "db_table": "leave_policies",
                "ordering": ["-is_active", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("max_days_per_year", models.IntegerField(default=10)),
                (
                    "is_paid",
                    models.BooleanField(
                        default=True,
                        help_text="Paid leave does not deduct from salary. Unpaid leave becomes LOP.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Leave Type",
                "verbose_name_plural": "Leave Types",
                "db_table": "leave_types",
            },
        ),
        migrations.CreateModel(
            name="PayrollInputAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20)),
                ("year", models.IntegerField()),
                (
                    "salary_type",
                    models.CharField(
                        choices=[("SALARY", "Salary"), ("STIPEND", "Stipend")],
                        default="SALARY",
                        max_length=20,
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("EARNING", "Earning"),
                            ("DEDUCTION", "Deduction"),
                            ("REIMBURSEMENT", "Reimbursement"),
                            ("ARREAR", "Arrear"),
                            ("BONUS", "Bonus"),
                            ("INCENTIVE", "Incentive"),
                            ("LOAN", "Loan Deduction"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='Human-readable label (e.g. "Diwali Bonus", "Laptop Reimbursement")',
                        max_length=100,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_taxable", models.BooleanField(default=False)),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="If True, carries forward to next month automatically",
                    ),
                ),
                ("remarks", models.TextField(blank=True, default="")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive adjustments are excluded from payroll calculation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payroll Input Adjustment",
                "verbose_name_plural": "Payroll Input Adjustments",
                "db_table": "payroll_input_adjustments",
                "ordering": ["-year", "-month", "employee__name"],
            },
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salary_type",
                    models.CharField(
                        choices=[("SALARY", "Salary"), ("STIPEND", "Stipend")],
                        max_length=20,
                    ),
                ),
                (
                    "annual_ctc",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Annual CTC"
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(default=django.db.models.functions.datetime.Now),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Salary Structure",
                "verbose_name_plural": "Salary Structures",
                "db_table": "salary_structures",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="TaxDeclaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "financial_year",
                    models.CharField(help_text="e.g. 2025-26", max_length=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft — not yet submitted"),
                            ("SUBMITTED", "Submitted — awaiting admin review"),
                            ("APPROVED", "Approved — used in TDS calculation"),
                            ("REJECTED", "Rejected — employee must revise"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                (
                    "lic_premium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "elss_investment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ppf_investment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "nsc_investment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "home_loan_principal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tuition_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other_80c",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "medical_insurance_self",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "medical_insurance_parents",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "parents_senior_citizen",
                    models.BooleanField(
                        default=False,
                        help_text="If True, parents 80D cap is ₹50,000 instead of ₹25,000",
                    ),
                ),
                (
                    "rent_paid_monthly",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "landlord_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "landlord_pan",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "city_type",
                    models.CharField(
                        choices=[("METRO", "Metro"), ("NON_METRO", "Non-Metro")],
                        default="NON_METRO",
                        help_text="Metro = 50% of Basic for HRA exemption; Non-Metro = 40%",
                        max_length=10,
                    ),
                ),
                (
                    "education_loan_interest",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "donations_80g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "donation_type",
                    models.CharField(
                        choices=[
                            ("100_PCT", "100% deduction (no limit)"),
                            ("50_PCT", "50% deduction (no limit)"),
                            (
                                "100_PCT_WITH_LIMIT",
                                "100% deduction (with 10% of income limit)",
                            ),
                            (
                                "50_PCT_WITH_LIMIT",
                                "50% deduction (with 10% of income limit)",
                            ),
                        ],
                        default="50_PCT",
                        help_text="Category of donation for 80G deduction calculation",
                        max_length=20,
                    ),
                ),
                (
                    "nps_additional",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Additional NPS contribution beyond employer contribution (max ₹50,000)",
                        max_digits=10,
                    ),
                ),
                (
                    "home_loan_interest",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Interest on home loan for self-occupied property (max ₹2,00,000)",
                        max_digits=10,
                    ),
                ),
                ("admin_remarks", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "proof_documents",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of uploaded proof document paths",
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tax Declaration",
                "verbose_name_plural": "Tax Declarations",
                "db_table": "tax_declarations",
                "ordering": ["-financial_year", "employee__name"],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("HR", "HR"),
                            ("PAYROLL", "Payroll"),
                            ("POLICY", "Policy Update"),
                            ("EVENT", "Event"),
                            ("URGENT", "Urgent"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "recipient_filter",
                    models.CharField(
                        default="ALL",
                        help_text="ALL or department_id or employee_id list",
                        max_length=50,
                    ),
                ),
                ("total_recipients", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "announcements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Employee ID must contain only uppercase letters and numbers.",
                                regex="^[A-Z0-9]+$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("dob", models.DateField(verbose_name="Date of Birth")),
                ("doj", models.DateField(verbose_name="Date of Joining")),
                (
                    "pan",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="PAN must be in format: ABCDE1234F",
                                regex="^[A-Z]{5}[0-9]{4}[A-Z]{1}$",
                            )
                        ],
                    ),
                ),
                (
                    "pf_number",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="PF Number"
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(max_length=30, verbose_name="Bank Account Number"),
                ),
                (
                    "bank_ifsc",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="IFSC must be in format: ABCD0123456",
                                regex="^[A-Z]{4}0[A-Z0-9]{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "pay_mode",
                    models.CharField(
                        choices=[
                            ("Bank Transfer", "Bank Transfer"),
                            ("NEFT", "NEFT"),
                            ("Cheque", "Cheque"),
                            ("Cash", "Cash"),
                        ],
                        default="NEFT",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                (
                    "health_card_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        help_text="Employee email for system login",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "personal_email",
                    models.CharField(
                        blank=True,
                        help_text="Personal email for welcome emails and communication",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="Temporary password for system access",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "password_changed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether employee has changed their initial password",
                    ),
                ),
                (
                    "password_set_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the password was set",
                        null=True,
                    ),
                ),
                (
                    "lpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual salary in lakhs (e.g., 4.5 for 4.5 LPA)",
                        max_digits=12,
                        null=True,
                        verbose_name="LPA (Lakhs Per Annum)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "account_activated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether employee has activated their account via invitation",
                    ),
                ),
                (
                    "onboarding_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether employee has completed the onboarding form",
                    ),
                ),
                (
                    "account_activated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the employee activated their account",
                        null=True,
                    ),
                ),
                (
                    "is_top_level_manager",
                    models.BooleanField(
                        default=False,
                        help_text="Marks this employee as a top-level manager node in the org chart",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="departments.department",
                    ),
                ),
                (
                    "reporting_manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Direct reporting manager for this employee",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to="employees.employee",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        help_text="Currently assigned shift",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="attendance.shift",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "db_table": "employees",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("WELCOME", "Welcome Email"),
                            ("PAYSLIP", "Payslip Email"),
                            ("BULK_WELCOME", "Bulk Welcome Email"),
                            ("RELIEVING", "Relieving Letter"),
                            ("EXPERIENCE", "Experience Letter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Log",
                "verbose_name_plural": "Email Logs",
                "db_table": "email_logs",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("delivered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="employees.announcement",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_receipts",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "db_table": "announcement_recipients",
                "ordering": ["-delivered_at"],
            },
        ),
        migrations.CreateModel(
            name="ActualSalaryCredited",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20)),
                ("year", models.IntegerField()),
                (
                    "actual_salary_credited",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_actual_salaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_salaries",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actual Salary Credited",
                "verbose_name_plural": "Actual Salaries Credited",
                "db_table": "actual_salary_credited",
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("sign_in_time", models.DateTimeField(blank=True, null=True)),
                ("sign_out_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Attendance",
                "verbose_name_plural": "Employee Attendance",
                "db_table": "employee_attendance",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PAN", "PAN Card"),
                            ("AADHAAR", "Aadhaar"),
                            ("BANK_DOC", "Bank Document"),
                            ("CERTIFICATE", "Certificate"),
                            ("OFFER_LETTER", "Offer Letter"),
                            ("APPOINTMENT_LETTER", "Appointment Letter"),
                            ("PROMOTION_LETTER", "Promotion Letter"),
                            ("PAYSLIP", "Payslip"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("document_name", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to="employee_documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE_ONLY", "Employee Only"),
                            ("ADMIN_ONLY", "Admin Only"),
                            ("BOTH", "Both"),
                        ],
                        default="BOTH",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="employees.employee",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Document",
                "verbose_name_plural": "Employee Documents",
                "db_table": "employee_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVATED", "Activated"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Invitation",
                "verbose_name_plural": "Employee Invitations",
                "db_table": "employee_invitations",
            },
        ),
        migrations.CreateModel(
            name="EmployeeLeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="Leave cycle start year this balance applies to (e.g. 2026 for FY 2026-27)"
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Opening balance created at leave-cycle start, including EL carry-forward.",
                        max_digits=6,
                    ),
                ),
                (
                    "allocated",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Total days allocated for the leave cycle, including monthly accruals.",
                        max_digits=5,
                    ),
                ),
                (
                    "used",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Days consumed by approved leave requests",
                        max_digits=5,
                    ),
                ),
                (
                    "encashed",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Earned leave days already encashed in the cycle.",
                        max_digits=5,
                    ),
                ),
                (
                    "last_accrual_processed_on",
                    models.DateField(
                        blank=True,
                        help_text="First day of the latest month for which EL accrual was processed.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="employees.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="employees.leavetype",
                    ),
                ),
            ],
            options={
                "db_table": "employee_leave_balances",
                "ordering": ["-year", "employee__name", "leave_type__name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "emergency_contact",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "bank_account",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("ifsc_code", models.CharField(blank=True, max_length=15, null=True)),
                ("pan_number", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="employee_photos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Profile",
                "verbose_name_plural": "Employee Profiles",
                "db_table": "employee_profiles",
            },
        ),
        migrations.CreateModel(
            name="EmployeeTaxProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "regime",
                    models.CharField(
                        choices=[("OLD", "Old Tax Regime"), ("NEW", "New Tax Regime")],
                        default="NEW",
                        help_text="Tax regime chosen by the employee. Defaults to NEW regime.",
                        max_length=5,
                    ),
                ),
                (
                    "is_tds_exempt",
                    models.BooleanField(
                        default=False,
                        help_text="If True, TDS computation is skipped for this employee entirely.",
                    ),
                ),
                (
                    "tds_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Manual monthly TDS override in rupees. If set, overrides the computed TDS for every payroll run. Use as an escape hatch for edge cases.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="HR notes about this employee's tax situation.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_profile",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Tax Profile",
                "verbose_name_plural": "Employee Tax Profiles",
                "db_table": "employee_tax_profiles",
            },
        ),
        migrations.CreateModel(
            name="LeaveEncashment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_year",
                    models.PositiveSmallIntegerField(
                        help_text="Leave cycle start year against which the encashment was processed."
                    ),
                ),
                ("requested_days", models.DecimalField(decimal_places=1, max_digits=5)),
                ("encashed_days", models.DecimalField(decimal_places=1, max_digits=5)),
                (
                    "basic_salary_snapshot",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "encash_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                        default="APPROVED",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_encashments",
                        to="employees.employee",
                    ),
                ),
                (
                    "leave_balance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encashments",
                        to="employees.employeeleavebalance",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_leave_encashments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Encashment",
                "verbose_name_plural": "Leave Encashments",
                "db_table": "leave_encashments",
                "ordering": ["-processed_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "paid_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Paid leave days approved against available balance.",
                        max_digits=5,
                    ),
                ),
                (
                    "lop_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Approved leave days treated as Loss of Pay.",
                        max_digits=5,
                    ),
                ),
                (
                    "lop_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimated payroll deduction for LOP days in this request.",
                        max_digits=12,
                    ),
                ),
                (
                    "day_breakdown",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Per-day approval breakdown. Each row contains date and PAID/LOP status.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="employees.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leave_requests",
                        to="employees.leavetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
                "db_table": "leave_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlySalaryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20)),
                ("year", models.IntegerField()),
                (
                    "salary_type",
                    models.CharField(
                        choices=[("SALARY", "Salary"), ("STIPEND", "Stipend")],
                        default="SALARY",
                        help_text="Salary type for this monthly data record",
                        max_length=20,
                    ),
                ),
                ("basic", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "hra",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="House Rent Allowance",
                    ),
                ),
                (
                    "da",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Dearness Allowance",
                    ),
                ),
                ("conveyance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("medical", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "special_allowance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pf_employee",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="PF Employee"
                    ),
                ),
                (
                    "professional_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pf_employer",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="PF Employer"
                    ),
                ),
                (
                    "other_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "salary_advance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("work_days", models.IntegerField()),
                ("days_in_month", models.IntegerField()),
                (
                    "lop_days",
                    models.IntegerField(default=0, verbose_name="Loss of Pay Days"),
                ),
                (
                    "lop_override",
                    models.IntegerField(
                        blank=True,
                        help_text="Manual LOP override. If set, overrides attendance-derived LOP.",
                        null=True,
                    ),
                ),
                (
                    "bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="One-time bonus for this month",
                        max_digits=10,
                    ),
                ),
                (
                    "incentive",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Performance incentive for this month",
                        max_digits=10,
                    ),
                ),
                (
                    "arrears",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Salary arrears (backdated revision payment)",
                        max_digits=10,
                    ),
                ),
                (
                    "reimbursement",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Expense reimbursements for this month",
                        max_digits=10,
                    ),
                ),
                (
                    "other_earning_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Any other one-time earning adjustment",
                        max_digits=10,
                    ),
                ),
                (
                    "other_deduction_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Any other one-time deduction adjustment",
                        max_digits=10,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, default="", help_text="HR notes for this month"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("EXCEL_IMPORT", "Excel Import"),
                            ("MANUAL_ENTRY", "Manual Entry"),
                        ],
                        default="EXCEL_IMPORT",
                        help_text="How this record was created",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_salaries",
                        to="employees.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_monthly_salaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_salaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Salary Data",
                "verbose_name_plural": "Monthly Salary Data",
                "db_table": "monthly_salary_data",
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("PAYSLIP_RELEASED", "Payslip Released"),
                            ("LEAVE_APPROVED", "Leave Approved"),
                            ("LEAVE_REJECTED", "Leave Rejected"),
                            ("DOCUMENT_UPLOADED", "Document Uploaded"),
                            ("ANNOUNCEMENT", "Announcement"),
                            ("ATTENDANCE_ALERT", "Attendance Alert"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("related_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
