# Generated by Django 4.2.7 on 2025-09-04 05:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("departments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Employee ID must contain only uppercase letters and numbers.",
                                regex="^[A-Z0-9]+$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("dob", models.DateField(verbose_name="Date of Birth")),
                ("doj", models.DateField(verbose_name="Date of Joining")),
                (
                    "pan",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="PAN must be in format: ABCDE1234F",
                                regex="^[A-Z]{5}[0-9]{4}[A-Z]{1}$",
                            )
                        ],
                    ),
                ),
                (
                    "pf_number",
                    models.CharField(max_length=20, verbose_name="PF Number"),
                ),
                (
                    "bank_account",
                    models.CharField(max_length=20, verbose_name="Bank Account Number"),
                ),
                (
                    "bank_ifsc",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="IFSC must be in format: ABCD0123456",
                                regex="^[A-Z]{4}0[A-Z0-9]{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "pay_mode",
                    models.CharField(
                        choices=[
                            ("NEFT", "NEFT"),
                            ("Cheque", "Cheque"),
                            ("Cash", "Cash"),
                        ],
                        default="NEFT",
                        max_length=10,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                (
                    "health_card_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "lpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual salary in lakhs (e.g., 4.5 for 4.5 LPA)",
                        max_digits=12,
                        null=True,
                        verbose_name="LPA (Lakhs Per Annum)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "db_table": "employees",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salary_type",
                    models.CharField(
                        choices=[("SALARY", "Salary"), ("STIPEND", "Stipend")],
                        max_length=20,
                    ),
                ),
                (
                    "annual_ctc",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Annual CTC"
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(default=django.db.models.functions.datetime.Now),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_structures",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary Structure",
                "verbose_name_plural": "Salary Structures",
                "db_table": "salary_structures",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="MonthlySalaryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20)),
                ("year", models.IntegerField()),
                ("basic", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "hra",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="House Rent Allowance",
                    ),
                ),
                (
                    "da",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Dearness Allowance",
                    ),
                ),
                ("conveyance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("medical", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "special_allowance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pf_employee",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="PF Employee"
                    ),
                ),
                (
                    "professional_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pf_employer",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="PF Employer"
                    ),
                ),
                (
                    "other_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "salary_advance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("work_days", models.IntegerField()),
                ("days_in_month", models.IntegerField()),
                (
                    "lop_days",
                    models.IntegerField(default=0, verbose_name="Loss of Pay Days"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_salaries",
                        to="employees.employee",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_salaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Salary Data",
                "verbose_name_plural": "Monthly Salary Data",
                "db_table": "monthly_salary_data",
                "ordering": ["-year", "-month"],
                "unique_together": {("employee", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="ActualSalaryCredited",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20)),
                ("year", models.IntegerField()),
                (
                    "actual_salary_credited",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_salaries",
                        to="employees.employee",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_actual_salaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Actual Salary Credited",
                "verbose_name_plural": "Actual Salaries Credited",
                "db_table": "actual_salary_credited",
                "ordering": ["-year", "-month"],
                "unique_together": {("employee", "month", "year")},
            },
        ),
    ]
