# Generated by Django 5.2.5 on 2026-04-20 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        ("payroll_config", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollinputadjustment",
            name="component",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to a SalaryComponent for classification",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payroll_adjustments",
                to="payroll_config.salarycomponent",
            ),
        ),
        migrations.AddField(
            model_name="payrollinputadjustment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_payroll_adjustments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payrollinputadjustment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payroll_adjustments",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="payrollinputadjustment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_payroll_adjustments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_structures",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="taxdeclaration",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_declarations",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="taxdeclaration",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_tax_declarations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="announcementrecipient",
            unique_together={("announcement", "employee")},
        ),
        migrations.AlterUniqueTogether(
            name="actualsalarycredited",
            unique_together={("employee", "month", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="employeeattendance",
            unique_together={("employee", "date")},
        ),
        migrations.AddIndex(
            model_name="employeeleavebalance",
            index=models.Index(fields=["employee", "year"], name="elb_emp_year_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="employeeleavebalance",
            unique_together={("employee", "leave_type", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="monthlysalarydata",
            unique_together={("employee", "month", "year", "salary_type")},
        ),
        migrations.AddIndex(
            model_name="payrollinputadjustment",
            index=models.Index(
                fields=["employee", "month", "year", "salary_type"],
                name="pia_emp_period_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollinputadjustment",
            index=models.Index(
                fields=["month", "year", "salary_type", "is_active"],
                name="pia_period_active_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taxdeclaration",
            unique_together={("employee", "financial_year")},
        ),
    ]
