# Generated by Django 4.2.7 on 2025-09-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0002_alter_employee_pay_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="bank_account",
            field=models.CharField(max_length=30, verbose_name="Bank Account Number"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="pf_number",
            field=models.CharField(max_length=30, verbose_name="PF Number"),
        ),
    ]
