# Generated by Django 4.2.7 on 2025-09-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0003_alter_employee_bank_account_alter_employee_pf_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="pf_number",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="PF Number"
            ),
        ),
    ]
