# Generated by Django 4.2.7 on 2025-09-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0004_make_pf_number_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="pay_mode",
            field=models.CharField(
                choices=[
                    ("Bank Transfer", "Bank Transfer"),
                    ("NEFT", "NEFT"),
                    ("Cheque", "Cheque"),
                    ("Cash", "Cash"),
                ],
                default="NEFT",
                max_length=20,
            ),
        ),
    ]
