# Generated by Django 4.2.7 on 2025-09-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_change_default_pay_mode_to_neft'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, help_text='Employee email for payslip delivery', max_length=255, null=True),
        ),
    ]
