# Generated by Django 4.2.7 on 2025-09-10 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0008_employee_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="bank_ifsc",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="IFSC must be in format: ABCD0123456",
                        regex="^[A-Z]{4}0[A-Z0-9]{6}$",
                    )
                ],
            ),
        ),
    ]
