# Generated by Django 4.2.7 on 2025-09-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0009_increase_bank_ifsc_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="Temporary password for system access",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="password_changed",
            field=models.BooleanField(
                default=False,
                help_text="Whether employee has changed their initial password",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="password_set_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When the password was set", null=True
            ),
        ),
    ]
