# Generated by Django 4.2.7 on 2025-09-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0010_employee_password_employee_password_changed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="personal_email",
            field=models.EmailField(
                blank=True,
                help_text="Personal email for welcome emails and communication",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Employee email for system login",
                max_length=255,
                null=True,
            ),
        ),
    ]
