# Generated by Django 4.2.7 on 2025-09-15 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0011_employee_personal_email_alter_employee_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("WELCOME", "Welcome Email"),
                            ("PAYSLIP", "Payslip Email"),
                            ("BULK_WELCOME", "Bulk Welcome Email"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Log",
                "verbose_name_plural": "Email Logs",
                "db_table": "email_logs",
                "ordering": ["-sent_at"],
            },
        ),
    ]
