# Generated by Django 4.2.7 on 2025-11-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0012_emaillog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("WELCOME", "Welcome Email"),
                    ("PAYSLIP", "Payslip Email"),
                    ("BULK_WELCOME", "Bulk Welcome Email"),
                    ("RELIEVING", "Relieving Letter"),
                ],
                max_length=20,
            ),
        ),
    ]
