# Generated by Django 4.2.7 on 2025-12-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0013_alter_emaillog_email_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("WELCOME", "Welcome Email"),
                    ("PAYSLIP", "Payslip Email"),
                    ("BULK_WELCOME", "Bulk Welcome Email"),
                    ("RELIEVING", "Relieving Letter"),
                    ("EXPERIENCE", "Experience Letter"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.CharField(
                blank=True,
                help_text="Employee email for system login",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="personal_email",
            field=models.CharField(
                blank=True,
                help_text="Personal email for welcome emails and communication",
                max_length=255,
                null=True,
            ),
        ),
    ]
