# Generated by Django 5.2.5 on 2026-03-12 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_attendancerecord_attendance__employe_4ca90e_idx_and_more"),
        ("employees", "0017_leavetype_employeedocument_leaverequest_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                help_text="Currently assigned shift",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="attendance.shift",
            ),
        ),
    ]
